const CHANGE_USER_INFO = 'CHANGE_USER_INFO'
const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
const UPDATE_DIRECTION = 'UPDATE_DIRECTION'
export {
  CHANGE_USER_INFO,
  UPDATE_USER_INFO,
  UPDATE_DIRECTION
}
