const CHANGE_USER_INFO = 'CHANGE_USER_INFO'
const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
const UPDATE_DIRECTION = 'UPDATE_DIRECTION'
const UPDATE_COURSE_LIST = 'UPDATE_COURSE_LIST'
const UPDATE_PHONE = 'UPDATE_PHONE'
export {
  CHANGE_USER_INFO,
  UPDATE_USER_INFO,
  UPDATE_DIRECTION,
  UPDATE_COURSE_LIST,
  UPDATE_PHONE
}
