const CHANGE_USER_INFO = 'CHANGE_USER_INFO'
const UPLOAD_USER_INFO = 'UPLOAD_USER_INFO'
const UPDATE_LESSON_LIST = 'UPDATE_LESSON_LIST'
const CHANGE_USER_STATUS = 'CHANGE_USER_STATUS'
export {
  CHANGE_USER_INFO,
  UPLOAD_USER_INFO,
  UPDATE_LESSON_LIST,
  CHANGE_USER_STATUS
}
