const CHANGE_USER_INFO = 'CHANGE_USER_INFO'
const UPLOAD_USER_INFO = 'UPLOAD_USER_INFO'
const UPDATE_LESSON_LIST = 'UPDATE_LESSON_LIST'
const CHANGE_USER_STATUS = 'CHANGE_USER_STATUS'
const UPLOAD_PHONE_NUM = 'UPLOAD_PHONE_NUM'
const UPDATEVERSION = 'UPDATEVERSION'
export {
  CHANGE_USER_INFO,
  UPLOAD_USER_INFO,
  UPDATE_LESSON_LIST,
  CHANGE_USER_STATUS,
  UPLOAD_PHONE_NUM,
  UPDATEVERSION
}
